<!-- GitHub Star -->
<iframe src="https://ghbtns.com/github-btn.html?user=nodekit-io&repo=nodekit&type=star&count=true" frameborder="0" scrolling="0" width="110px" height="20px"></iframe>
<!-- GitHub fork -->
<iframe src="https://ghbtns.com/github-btn.html?user=nodekit-io&repo=nodekit&type=fork&count=true" frameborder="0" scrolling="0" width="110px" height="20px"></iframe>
<!-- Tweet button -->
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://nodekit.io/" data-text="NodeKit is the universal, open-source, embedded Node.js engine for MacOS, iOS, Android, and Windows." data-hashtags="nodekit">Tweet</a>
<!-- Twitter follow button -->
<a href="https://twitter.com/nodekit_io" class="twitter-follow-button" data-show-count="false">Follow @nodekitio</a>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
</script>